### ISSUE TITLE
when using "Release control" on giant his texture is faling in the ground, but hit boxes working right

### ISSUE THREAD

**Issue by superstrongbozo** [Test-Account666/LethalCompany-ControlCompanyAddons#3]
![image](https://github.com/TheBlackEntity/LethalCompany-ControlCompanyAddons/assets/166734896/17140773-6395-49f2-b170-57a19c6c2da3)

**Comment by superstrongbozo** [comment]
![image](https://github.com/TheBlackEntity/LethalCompany-ControlCompanyAddons/assets/166734896/55dfdb05-9bce-4153-ab92-ef3530783ab3)
(his head)

**Comment by superstrongbozo** [comment]
eating animation
![image](https://github.com/TheBlackEntity/LethalCompany-ControlCompanyAddons/assets/166734896/0e4831b4-5f34-4dbf-a59a-e103793dd0af)

**Comment by Test-Account666** [comment]
Oh... Forgot about respawn animations...

**Comment by Test-Account666** [comment]
Fixed in 1.2.3
