### ISSUE TITLE
Release control option

### ISSUE THREAD

**Issue by HyperUndone** [Test-Account666/LethalCompany-ControlCompanyAddons#5]
I'm not exactly sure what happened but the release control option used to be available but then a week later it doesn't seem to show up anymore.

**Comment by Test-Account666** [comment]
Thanks for the information, I'll have a look

**Comment by HyperUndone** [comment]
i found out it has something to do with the scopophobia mod which adds the shy guy scp enemy

**Comment by Test-Account666** [comment]
Looking at how old this issue is and that the feature works just fine for me, I'll close this issue
