### ISSUE TITLE
[Feature Request] Player ESP

### ISSUE THREAD

**Issue by DeadShot187xx** [Test-Account666/LethalCompany-ControlCompanyAddons#7]
I think a pkayer esp would be nice, so you can see players and know where they are to kill them. It'd make playing Jester and Bracken easier, since you would always know where people are.

**Comment by Test-Account666** [comment]
I'm already working on one :)

**Comment by DeadShot187xx** [comment]
That's great, but when would it be out? (like just a rough time)
I know that you're one person but the stuff you made on this mod is already great.

**Comment by Test-Account666** [comment]
> That's great, but when would it be out? (like just a rough time)
> I know that you're one person but the stuff you made on this mod is already great.

I'll try to get it done this week, but cannot promise anything

**Comment by Ishdhd** [comment]
responding on an alt but hope it’s out soon! good luck
