### ISSUE TITLE
ESP Broken?

### ISSUE THREAD

**Issue by DeadShot187xx** [Test-Account666/LethalCompany-ControlCompanyAddons#8]
This could be due to using a fog removal mod (RemoverOfFog) but the esp doesn't highlight players through walls AND the player model becomes very glitchy and the esp kinda spazzes out (when testing)

**Comment by DeadShot187xx** [comment]
I don't know if it's because I'm rendering myself, but idk. Would need to test on friends.

**Comment by DeadShot187xx** [comment]
Video showing bug?
https://streamable.com/gdhito

**Comment by Test-Account666** [comment]
Can you test it without any other mods installed?

**Comment by Test-Account666** [comment]
Version 2.0.0 should fix your issue

**Comment by Ishdhd** [comment]
On my phone again but okay, I’ll go test it and tell you the results

**Comment by DeadShot187xx** [comment]
Alright, weird bug already. Entering thunderstore MM client, can't update it and it's still set to v 1.3.0. Trying to fix now.

**Comment by DeadShot187xx** [comment]
Lemme try booting up the game.

**Comment by DeadShot187xx** [comment]
It's the nonfixed ESP, is this an issue on Thunderstore?

**Comment by Test-Account666** [comment]
Can you test it without any other mods installed?



> It's the nonfixed ESP, is this an issue on Thunderstore?

Thunderstore needs an hour or so to know about the update

**Comment by Test-Account666** [comment]
Just give it another 40 minutes :)

**Comment by DeadShot187xx** [comment]
Ohhh, alright. Thanks! Other than that I will say that the mod is fantastic. Thanks a lot for making this.

**Comment by DeadShot187xx** [comment]
It's great, the only thing I have to say now is that when using the night vision (on monsters) it makes the esp a bit harder to see. That's all.
