### ISSUE TITLE
ESP Breaks Player model?

### ISSUE THREAD

**Issue by DeadShot187xx** [Test-Account666/LethalCompany-ControlCompanyAddons#9]
Whenever I use ESP, it'll activate kinda? It'll first delete all player models making them invisible other than their nametag, then after using ESP again it fixes and works. But the invisible player part becomes partially permanent. It's pretty annoying and _POSSIBLY_ caused a DeSync issues in my lobby such as invisible trees, invisible Jester (after spawned by me, one of my friends could not see it. same for a barber i spawned.) These issues make it a lot harder to troll my friends so a fix soon for these problems, or at least the first one would be nice.

**Comment by DeadShot187xx** [comment]
Update: Doing a test, the issue is due to LetMeLookDown v1.0.1 by FlipMods. Please add compatibility for it :D

**Comment by DeadShot187xx** [comment]
Update AGAIN. It still will break if you spam the ESP key a couple times.

**Comment by DeadShot187xx** [comment]
UPDATE AGAIN AGAINm found out it also breaks if you enter another save after leaving a save.

**Comment by Test-Account666** [comment]
I'll be re-doing the esp next update

**Comment by DeadShot187xx** [comment]
Last update on the esp issue: It seems to break after using it for the first time when launching. So you can leave and rejoin saves and if you haven't used it prior it'll work. If you then try to use it after using it, it'll break.

**Comment by Test-Account666** [comment]
Should finally be fixed in 2.0.1, sorry for the wait
